package com.formulario;

import javax.swing.JOptionPane;

/**
 *
 * @author loren
 */
public class FormularioGUI extends javax.swing.JFrame {
    //Instancia de la clase ProcesarDatos
    ProcesarDatos datosProcesados = new ProcesarDatos();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioGUI.class.getName());

    /**
     * Creates new form FormularioGUI
     */
    public FormularioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        plTitulo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        txtMatricula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCuatri = new javax.swing.JTextField();
        btnCapturar = new javax.swing.JButton();
        btnPresentar = new javax.swing.JButton();
        lbMatricula = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbCuatri = new javax.swing.JLabel();
        btnResetear = new javax.swing.JButton();
        plTitulo1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plTitulo.setBackground(new java.awt.Color(204, 228, 255));
        plTitulo.setForeground(new java.awt.Color(204, 204, 255));
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        plTitulo.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        plTitulo.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 260, -1));

        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        plTitulo.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 260, -1));

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        plTitulo.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 260, -1));

        txtCuatri.setBackground(new java.awt.Color(255, 255, 255));
        plTitulo.add(txtCuatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, -1));

        btnCapturar.setBackground(new java.awt.Color(0, 51, 153));
        btnCapturar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnCapturar.setForeground(new java.awt.Color(255, 255, 255));
        btnCapturar.setText("Capturar");
        btnCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarActionPerformed(evt);
            }
        });
        plTitulo.add(btnCapturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnPresentar.setBackground(new java.awt.Color(0, 51, 153));
        btnPresentar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnPresentar.setForeground(new java.awt.Color(255, 255, 255));
        btnPresentar.setText("Presentar");
        btnPresentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentarActionPerformed(evt);
            }
        });
        plTitulo.add(btnPresentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        lbMatricula.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        lbMatricula.setForeground(new java.awt.Color(0, 0, 0));
        lbMatricula.setText("Matrícula:");
        plTitulo.add(lbMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        lbNombres.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        lbNombres.setForeground(new java.awt.Color(0, 0, 0));
        lbNombres.setText("Nombres:");
        plTitulo.add(lbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lbApellidos.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        lbApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lbApellidos.setText("Apellidos:");
        plTitulo.add(lbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        lbCuatri.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        lbCuatri.setForeground(new java.awt.Color(0, 0, 0));
        lbCuatri.setText("Cuatrimestreste Cursado:");
        plTitulo.add(lbCuatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 170, 30));

        btnResetear.setBackground(new java.awt.Color(0, 51, 153));
        btnResetear.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnResetear.setForeground(new java.awt.Color(255, 255, 255));
        btnResetear.setText("Resetear");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });
        plTitulo.add(btnResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        plTitulo1.setBackground(new java.awt.Color(0, 51, 153));
        plTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 51, 153));
        jTextField1.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("DATOS PERSONALES");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        plTitulo1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(plTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(plTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 341, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnPresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentarActionPerformed

        JOptionPane.showMessageDialog(this, datosProcesados.presentarDatos());
            }//GEN-LAST:event_btnPresentarActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void btnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarActionPerformed
    //valida que ningun campo este vacío
        if (txtMatricula.getText().trim().isEmpty() ||
        txtNombres.getText().trim().isEmpty() ||
        txtApellidos.getText().trim().isEmpty() ||
        txtCuatri.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(null,"Por favor, complete todos los campos obligatorios.");
    return;
    }
    //si no hay campos vacíos se capturan los datos
    String matricula = txtMatricula.getText();
    String nombres = txtNombres.getText();
    String apellidos = txtApellidos.getText();
    String cuatrimestre = txtCuatri.getText();
    datosProcesados.capturarDatos(matricula, nombres, apellidos, cuatrimestre);
    JOptionPane.showMessageDialog(this, "Datos capturados correctamente");
    }//GEN-LAST:event_btnCapturarActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
    limpiarCampos();    }//GEN-LAST:event_btnResetearActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
    char c = evt.getKeyChar(); 
    if (!Character.isLetter(c)&& !Character.isWhitespace(c)){
    JOptionPane.showMessageDialog(null, "Favor ingresar solo letras");
    evt.consume();}
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
    char c = evt.getKeyChar(); 
    if (!Character.isLetter(c)&& !Character.isWhitespace(c)){
    JOptionPane.showMessageDialog(null, "Favor ingresar solo letras");
    evt.consume();}
    }//GEN-LAST:event_txtApellidosKeyTyped
    
    private void limpiarCampos(){
    txtMatricula.setText("");
    txtNombres.setText("");
    txtApellidos.setText("");
    txtCuatri.setText("");
    txtMatricula.requestFocus();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturar;
    private javax.swing.JButton btnPresentar;
    private javax.swing.JButton btnResetear;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbCuatri;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plTitulo1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCuatri;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
